
### -- Database Configuration
### A must-fill-in ! - What are the details for the database.

database-address:
database-schema:
database-username:
database-password:


### -- Discord Bot Configuration
### Another must-fill-in! The bot is the second half of this project that allows
### you to actually link your account.

# Make your own app here: https://discord.com/developers/applications
bot-token:

# How should the bot behave on each of these servers.
server-configs:
  id-here:  # This bot can handle different discord servers differently.
    short-name: a-server
    member-role-id:  # Leave empty to allow everyone to join
    admin-role-id:   # Allows auto-op for certain roles Leaving this empty skips this behaviour.
    missing-member-role-message: # Allows you to do a cheeky ad for memberships.



### -- General Pairing Configuration
### Configures the more general parts of account linking.

# How many minecraft accounts can be paired to 1 discord account
# Set to two by default with the intention to allow one bedrock + one java
paired-account-limit: 2

# Should all pending links be cleared when the server starts?
prune-pending-links-on-restart: true

# Used in link message - helps signpost people to the right place to /link.
link-location: the Discord server

# When linking on the discord side, show a notice with how data will be used.
show-gdpr-consent: true

# Appends a short note to the end of the in-game linking menu. Useful for small clarifications.
discord-link-hint: /link can be used in any channel of that server - It's only visible to you.



### -- Pairing Codes
### How should pairing codes be generated? This section pretty much determines that.
### Example:  goose-like-gold

# How many words should a pairing code have. Lower is better for memorising but higher
# reduces collisions. Balance this with the amount of available words for the best result.
pairing-code-blocks: 3

# How many times should the server try to generate a code, in the case that there are
# conflicts, before giving up.
paring-code-generation-attempts: 3

# Pairing Code Word List
# Change this if anything offensive comes up.
pairing-word-list:
  - goose
  - zombie
  - pig
  - allay
  - fox
  - wolf
  - villager
  - dragon
  - enderman
  - creeper
  - craft
  - like
  - very
  - mine
  - coal
  - iron
  - gold
  - copper
  - redstone
  - lapis
  - emerald
  - ruby
  - diamond
  - smash
  - minecraft
  - terraria
  - rain
  - risk
  - shiny
  - dull
  - rusty
  - rainbow
  - poggers
  - purple
  - solar
  - lunar
  - star
  - bedrock
  - java
  - portal
  - nether
  - end
  - water
  - lava
  - hint
  - sea
  - air
  - land